version: '3'

services:
  api-college:
    build: 
      context: .
      dockerfile: docker/Dockerfile
    image: api_college
    volumes:
      - .:/src
      - /src/node_modules
    ports:
      - $PORT:$PORT
  postgresql:
    container_name: db_college_pg
    image: postgres:14-alpine
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: db_college
      POSTGRES_PASSWORD: db_college
      POSTGRES_USER: db_college