export { GetStudent } from './GetStudent'
export { GetAllStudents } from './GetAllStudents'
export { GetStudentSubjects } from './GetStudentSubjects'
export { GetStudentHistoric } from './GetStudentHistoric'
export { CreateStudent } from './CreateStudent'
