export { GetStudent } from './GetStudent'
export { GetAllStudents } from './GetAllStudents'
export { GetStudentSubjects } from './GetStudentSubjects'
export { GetStudentHistoric } from './GetStudentHistoric'
export { CreateStudent } from './CreateStudent'
export { UpdateStudent } from './UpdateStudent'
export { DeleteStudent } from './DeleteStudent'
